services:
  - type: web
    name: dockhub-backend
    runtime: docker
    dockerContext: ./dockhub_backend
    dockerfilePath: ./dockhub_backend/Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /docs
    envVars:
      - key: PORT
        value: 10000
