services:
  - type: web
    name: dockhub-backend
    runtime: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /docs
    envVars:
      - key: PORT
        value: 10000
